export const coldDrinks = {
    alcohol: [
        { "name": "Espresso Martini", destination: "./espressomartini.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "50mL vodka/20mL (~2 pumps) irish cream syrup/20mL (~2 pumps) coffee liquor/1 shot espresso/Shake until foam/3 beans on top in the shape of a triangle", mainSize: "Dine in (martini cup)", availableSizes: ["400cc: same"] }
    ],
    espresso: [
        { "name": "Iced Americano", destination: "./icedamericano.html", color: "#4E2A2A", cup: "Bigger Espresso Cup", steps: "Double Shot/8 ice cubes/160mL water", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: 3 shots/10 ice cubes/200mL water"] },
    ],
    frappe: [
        { "name": "Noix", destination: "./noix.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "120mL Milk + 1 cup ice/1 espresso shot/1 scoop (40g) toffee caramel powder/2 pumps toffee crunch syrup/3-4 coffee beans/blend/whipped cream on top/caramel sauce on top", mainSize: "Dine in (smoothie cup)", availableSizes: ["400cc: same"] },
        { "name": "Mocha Original", destination: "./mochaoriginal.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "120mL Milk + 1 cup ice/single shot/1 scoop (40g) mocha powder/2 pumps irish cream syrup/blend", mainSize: "Dine in (smoothie cup)", availableSizes: ["400cc: same"] },
        { "name": "Mocha Tiramisu", destination: "./mochatiramisu.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "120mL Milk + 1 cup ice/single shot/1 scoop (40g) mocha powder/2 pumps tiramisu syrup/blend", mainSize: "Dine in (smoothie cup)", availableSizes: ["400cc: same"] },
        { "name": "Caramel Frappe", destination: "./caramelfrappe.html", color: "#FFD59A", cup: "Small Espresso Cup", steps: "100mL milk + 1 cup ice/single shot/2 pumps caramel sauce/1 pump caramel syrup/0.5 scoop vanilla(20g)/blend", mainSize: "Dine in (smoothie cup)", availableSizes: ["400cc: same"] },
        { "name": "Coffee Frappe", destination: "./coffeefrappe.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "100mL milk + 1 cup ice/single shot/0.5 scoop vanilla (20g)/2 pumps irish cream/5 coffee beans/blend", mainSize: "Dine in (smoothie cup)", availableSizes: ["400cc: same"] },
        { "name": "White Mocha", destination: "./whitemochafrappe.html", color: "#FFD59A", cup: "Small Espresso Cup", steps: "120mL Milk + 1 cup ice/single shot/1 scoop (40g) white chocolate powder/2.5 pumps white chocolate sauce/blend", mainSize: "Dine in (smoothie cup)", availableSizes: ["400cc: same"] },
        { "name": "Salted Caramel", destination: "./saltedcaramel.html", color: "#80532d", cup: "Small Espresso Cup", steps: "100mL milk + 1 cup ice/single shot/35g salted caramel powder/2 pumps salted caramel syrup/blend", mainSize: "Dine in (smoothie cup)", availableSizes: ["400cc: same"] },
        { "name": "Pumpkin Spice", destination: "./pumpkinspice.html", color: "#FF7518", special: 1, cup: "Small Espresso Cup", steps: "100mL Milk + 1 cup ice/Espresso Shot (Optional)/1 scoop (40g) Pumpkin spice powder/2 pumps pumpkin spice syrup/blend/Whipped Cream + Cinnamon powder on top", mainSize: "Dine in (Smoothie Cup)", availableSizes: ["400cc: same"] },
        { "name": "Red Velvet", destination: "./redvelvet.html", color: "#9c0000", special: 1, cup: "Small Espresso Cup", steps: "1 scoop red velvet(40g)/3 pumps rose syrup/120mL milk/1 cup ice/blend/whipped cream + red sprinkles on top ", mainSize: "Dine in (smoothie cup)", availableSizes: ["400cc: same"] },
    ],
    latte: [
        { "name": "Iced Latte", destination: "./iced.html", color: "#6F6E39", cup: "Small Espresso Cup", steps: "full ice/250mL Milk/1 shot on top", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: full ice/300mL Milk/2 shots on top"] },
        { "name": "Matcha", destination: "./matcha.html", color: "#69bf64", cup: "Small Espresso Cup", steps: "3g Matcha Powder/~4 Ice Cubes in shaker/250mL Milk/Shake/~4 new ice cubes in cup/drain matcha out of shaker without ice cubes", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: 4g Matcha Powder/~4 Ice Cubes in shaker/300mL Milk/Shake/~5 new ice cubes in cup/drain matcha out of shaker without ice cubes"] },
        { "name": "Strawberry/Mango Matcha", destination: "./smmatcha.html", backgroundImage: 'linear-gradient(to right, #FA5053,orange, #69bf64)', cup: "Small Espresso Cup", steps: "3g matcha powder in bowl/40mL hot water/whisk in bowl/40mL Strawberry or Mango puree (Dr. Smoothie) in cup/4 ice cubes/120mL milk/add matcha mixture on top", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: 4g matcha powder in bowl/40mL hot water/whisk in bowl/60mL Strawberry or Mango puree (Dr. Smoothie) in cup/4 ice cubes/180mL milk/add matcha mixture on top"] },
        { "name": "Pink Cloud Matcha", destination: "./pcmatcha.html", color: "#EF2B7C", cup: "Small Espresso Cup", steps: "3g Matcha Powder in bowl/2 pumps vanilla syrup/40mL hot water/whisk in bowl/~4 new ice cubes in cup/250mL milk/add matcha mixture on top/Whisk 75mL whipping cream with a pinch of beetroot powder/Add on top of matcha", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same"] },
        { "name": "Blue Curacao", destination: "./bluecuracao.html", color: "#1a305e", cup: "Small Espresso Cup", steps: "1 pump blue curacao syrup/a bit of milk in bottom of cup/mix well until light blue color/~4 Ice Cubes/250mL Milk slowly so they dont mix/single shot on top", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: 2 pump blue curacao syrup/a bit of milk in bottom of cup/mix well until light blue color/~6 Ice Cubes/300mL Milk slowly so they dont mix/double shot on top"] },
        { "name": "Vanilla", destination: "./vanilla.html", color: "#F3E5AB", cup: "Small Espresso Cup", steps: "full ice/250mL Milk/2 pumps vanilla syrup/stir well/1 shot on top", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: full ice/300mL Milk/3 pumps vanilla syrup/stir well/2 shots on top"] },
        { "name": "Caramel", destination: "./caramel.html", color: "#C68E17", cup: "Small Espresso Cup", steps: "full ice/250mL Milk/2 pumps caramel syrup/stir well/1 shot on top", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: full ice/300mL Milk/3 pumps caramel syrup/stir well/2 shots on top"] },
        { "name": "Cinnamon", destination: "./cinnamon.html", color: "#D2691E", cup: "Small Espresso Cup", steps: "full ice/250mL Milk/2 pumps cinnamon syrup/stir well/1 shot on top", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: full ice/300mL Milk/3 pumps cinnamon syrup/stir well/2 shots on top"] },
        { "name": "Hazelnut", destination: "./hazelnut.html", color: "#ae9f80 ", cup: "Small Espresso Cup", steps: "full ice/250mL Milk/2 pumps hazelnut syrup/stir well/1 shot on top", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: full ice/300mL Milk/3 pumps hazelnut syrup/stir well/2 shots on top"] },
        //{"name": "Turmeric", destination: "./turmeric.html", color: "#D2691E"},
        { "name": "Rose", destination: "./rose.html", color: "#FF69B4", cup: "Small Espresso Cup", steps: "3 drops red food coloring/2 pumps Rose syrup/~4 ice cubes in shaker/250mL Milk/Shaken/~4 new ice cubes in cup/drain shaker without old ice", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: 5 drops red food coloring/3 pumps Rose syrup/~6 ice cubes in shaker/300mL Milk/Shaken/~6 new ice cubes in cup/drain shaker without old ice"] },
        { "name": "Red Velvet", destination: "./redvelvet.html", color: "#9c0000", special: 1, cup: "400cc", steps: "1 scoop red velvet (40g)/2 pumps rose syrup/200mL milk/shake/1 cup full ice", mainSize: "Dine in: 400cc", availableSizes: ["400cc: same", "500cc: 1 scoop red velvet (40g)/3 pumps rose syrup/250mL milk/shake/1 cup full ice"] },
        { "name": "Charcoal", destination: "./charcoal.html", color: "#333333", cup: "Small Espresso Cup", steps: "Single Shot/15g Charcoal powder/~4 ice cubes/250mL Milk/Shaken/~4 new ice cubes in cup/drain shaker without old ice cubes", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: Double Shot/20g Charcoal powder/~6 ice cubes/300mL Milk/Shaken/~6 new ice cubes in cup/drain shaker without old ice cubes"] },
        { "name": "Iced Mocha", destination: "./icedmocha.html", color: "#30210c", cup: "Small Espresso Cup", steps: "2 pumps chocolate sauce in cup/Single shot/Stir until mocha is very well dissolved/~4 Ice Cubes/250mL Milk/stir entire drink until uniform color", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: 3 pumps chocolate sauce in cup/double shot/Stir until mocha is very well dissolved/~6 Ice Cubes/300mL Milk/stir entire drink until uniform color"] },
        { "name": "Iced White Mocha", destination: "./icedwhitemocha.html", color: "#ffe1b8", cup: "Small Espresso Cup", steps: "2.5 pumps white chocolate sauce in cup/Single shot/Stir until white mocha is very well dissolved/~4 Ice Cubes/250mL Milk/stir entire drink until uniform color", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: 3.5 pumps white chocolate sauce in cup/Double shot/Stir until white mocha is very well dissolved/~6 Ice Cubes/300mL Milk/stir entire drink until uniform color"] },
        { "name": "Iced Spanish", destination: "./spanishlatte.html", color: "#6F6E39", cup: "Small Espresso Cup", steps: "45g condensed milk/Single shot/Stir until condensed milk is very well dissolved/~4 Ice Cubes/250mL Milk/stir entire drink until uniform color", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: 65g condensed milk/double shot/Stir until condensed milk is very well dissolved/~6 Ice Cubes/300mL Milk/stir entire drink until uniform color"] },
        { "name": "Iced Caramel Macchiato", destination: "./caramelmacchiato.html", color: "#ffcb6b", cup: "Small Espresso Cup", steps: "Foam with French Press/Double Shot/3 Vanilla Syrup pumps/~4 Ice Cubes/250mL Milk/15g Caramel on foam (design)/<a href='#garnish'>click to see garnish pattern", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: Foam with french press/ 3 shots/4 pumps vanilla syrup/300mL milk/15g caramel on top of foam (design)/4 ice cubes"] },
        { "name": "White Mocha Caramel", destination: "./whitemochacaramel.html", color: "#fcb738", cup: "Small Espresso Cup", steps: "Single espresso shot/2 pumps Caramel sauce/1 pump White Chocolate sauce/4 ice cubes/250mL Milk/5g Caramel Sauce (design)/<a href='#garnish'>click to see garnish pattern", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: Double shot/2.5 pumps caramel sauce/1.5 pumps white chocolate sauce/4 ice cubes/300mL milk/5g caramel sauce on top"] },
        { "name": "Salted Caramel Mocha", destination: "./saltedcaramelmocha.html", color: "#5c3c00", cup: "Small Espresso Cup", steps: "Single shot/2 pumps chocolate sauce/1.5 pumps salted caramel syrup/250mL milk/4 ice cubes/foam in french press/5g chocolate sauce on top/<a href='#garnish'>click to see garnish pattern", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: Double shot/2.5 pumps chocolate sauce/2 pumps salted caramel syrup/300mL milk/5g chocolate sauce on top/4 ice cubes"] },
    ],
    lemonade: [
        { "name": "Minted Lemonade", destination: "./mintedlemonade.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "40mL Lime Pure/2 pumps yuzu lime syrup/65mL water/6 mint leaves/~1 cup ice cubes", mainSize: "Dine in (smoothie cup)", availableSizes: ["400cc: same"] },
        { "name": "Lemonade", destination: "./lemonade.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "40mL Lime Pure/2 pumps yuzu lime syrup/65mL water/~1 cup ice cubes", mainSize: "Dine in (smoothie cup)", availableSizes: ["400cc: same"] },
    ],
    milkshake: [
        { "name": "Lotus Caramel", destination: "./lotuscaramel.html", color: "#DDAD75", cup: "Small Espresso Cup", steps: "120mL milk + 1 cup ice/15g vanilla powder/1 pump caramel sauce/1 pump speculoos syrup/1 tea spoon lotus spread (30g)/blend./whipped cream on top/crushed lotus on top", mainSize: "Dine in (milkshake cup)", availableSizes: ["400cc: same"] },
        { "name": "Cookies and Cream", destination: "./cookiesandcream.html", color: "#333", cup: "Small Espresso Cup", steps: "120mL milk + 1 cup ice/1 scoop cookies & cream powder (40g)/2 pumps chocolate cookie syrup/blend./drizzle cup with chocolate sauce/whipped cream on top/crushed oreo on top", mainSize: "Dine in (milkshake cup)", availableSizes: ["400cc: same"] },
        { "name": "Nutty Bueno", destination: "./nuttybueno.html", color: "#1B1B1B", cup: "Small Espresso Cup", steps: "120mL milk + 1 cup ice/1 scoop (40g) monbana chocolate powder/0.25 scoop (10g) vanilla powder/2 pumps bueno syrup/0.5 pumps chocolate hazelnut sauce/blend./drizzle cup with chocolate hazelnut sauce/whipped cream on top/chocolate hazelnut sauce on top", mainSize: "Dine in (milkshake cup)", availableSizes: ["400cc: same"] },
        { "name": "Vanilla Strawberry", destination: "./vanillastrawberry.html", color: "#FB2943", cup: "Small Espresso Cup", steps: "120mL milk + 1 cup ice/30mL Strawberry Syrup/20mL Strawberry Sauce (mixer)/0.5 scoop (20g) Vanilla/blend./whipped cream on top/5g strawberry on top", mainSize: "Dine in (milkshake cup)", availableSizes: ["400cc: same"] },
        { "name": "Pistachio", destination: "./pistachio.html", color: "#93C572", cup: "Small Espresso Cup", steps: "100mL milk + 1 cup ice/0.5 or 1 pump rose syrup/35g Pistachio Powder/10g Vanilla Powder/blend./whipped cream on top", mainSize: "Dine in (milkshake cup)", availableSizes: ["400cc: same"] },
        { "name": "Ruby Chocolate", destination: "./rubychocolate.html", color: "#E0115F", cup: "Small Espresso Cup", steps: "100mL milk + 1 cup ice/3 pumps Ruby syrup/15g white chocolate Powder/0.5 pump white mocha sauce/blend./whipped cream on top", mainSize: "Dine in (milkshake cup)", availableSizes: ["400cc: same"] },
        { "name": "Vanilla", destination: "./vanilla.html", color: "#F3E5AB", cup: "Small Espresso Cup", steps: "100mL milk + 1 cup ice/30g Vanilla powder/2.5 pumps vanilla syrup/1 pump white mocha/blend./whipped cream on top", mainSize: "Dine in (milkshake cup)", availableSizes: ["400cc: same"] },
        // {"name": "Brownie", destination: "./brownie.html", color: "#4f2a2a"},
        { "name": "Blueberry Muffin", destination: "./blueberrymuffin.html", color: "#464196", cup: "Small Espresso Cup", steps: "100mL milk + 1 cup ice/40mL blueberry sauce (mixer)/2 pumps blueberry muffin syrup/10g vanilla powder/blend./whipped cream on top", mainSize: "Dine in (milkshake cup)", availableSizes: ["400cc: same"] }
    ],
    other: [
        { "name": "Lotus Affogato", destination: "./lotusaffogato.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "1 crushed lotus cookie in bottom of cup/cover with 100g vanilla merry cream/single shot on top", mainSize: "Dine in (martini cup)", availableSizes: ["400cc: same"] },
        { "name": "Iced Chocolate", destination: "./icedchocolate.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "35g Chocolate powder/1 pump chocolate sauce/0.25 pumps vanilla syrup/250mL Milk/4 ice cubes/Shaken/Whipped Cream/Chocolate sauce on whipped cream", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: 50g Chocolate powder/1.5 Chocolate Pumps/300mL Milk/4 ice cubes/shaken/whipped cream on top/chocolate sauce on whipped cream"] },
        { "name": "Minted Lemonade", destination: "./mintedlemonade.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "40mL Lime Pure/2 pumps yuzu lime syrup/100mL water/6 mint leaves/~1 cup ice cubes", mainSize: "Dine in (smoothie cup)", availableSizes: ["400cc: same"] },
    ],
    smoothie: [
        { "name": "PAP", destination: "./peach.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "100mL Dr. Smoothie PAP/75mL water/1 cup ice cubes/blend", mainSize: "Dine in (milkshake cup)", availableSizes: ["400cc: same", "500cc: 150mL dr. smoothie PAP/100ml water/1 cup ice cubes/ blend"] },
        //{"name": "Mixed Berries Smoothie", destination: "./mixedberries.html", color: "#4E2A2A"},
        { "name": "Mango", destination: "./mango.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "100mL Dr. Smoothie Mango/75mL water/1 cup ice cubes/blend", mainSize: "Dine in (milkshake cup)", availableSizes: ["400cc: same", "500cc: 150mL dr. smoothie mango/ 100mL water/1 cup ice cubes/blend"] },
        { "name": "Strawberry Lychee", destination: "./barbie.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "100mL Dr. Smoothie Strawberry/2 pumps lychee/75mL water/1 cup ice cubes/blend", mainSize: "Dine in (milkshake cup)", availableSizes: ["400cc: same", "500cc: 150ml strawberry puree/3 pumps lychee/full cup ice/100mL water/blend"] },
        { "name": "Passionfruit", destination: "./passionfruit.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "40mL passionfruit (mixer)/2 pumps passionfruit syrup/75mL water/1 cup ice cubes/blend", mainSize: "Dine in (milkshake cup)", availableSizes: ["400cc: same", "500cc: 50mL passionfruit (mixer)/3 pumps passionfruit syrup/85mL water/1 cup ice cubes/blend"] }
    ],
    icedTea: [
        { "name": "Iced Passionfruit + Mango", destination: "./passionfruitmango.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "2 pumps passionfruit/3 pumps mango/120 mL water/fill small shaker cup ice/Shake", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: 2.5 pumps passionfruit/3.5 pumps mango/150mL water/fill small shaker cup with ice/shake"] },
        { "name": "Iced Lemon", destination: "./icedlemon.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "5 pumps Iced tea lemon syrup/120 mL water/fill small shaker cup ice/Shake", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: 6 pumps lemon syrup/150mL water/fill small shaker cup with ice/shake"] },
        { "name": "Iced Peach", destination: "./icedpeach.html", color: "#4E2A2A", cup: "Small Espresso Cup", steps: "5 pumps Peach syrup/120 mL water/fill small shaker cup ice/Shake", mainSize: "Dine in (small can cup)", availableSizes: ["400cc: same", "500cc: 6 pumps peach syrup/150mL water/fill small shaker cup with ice/shake"] },
    ]
}